# Generated by Django 6.0.6 on 2026-07-17 00:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_ID', models.UUIDField(default=uuid.uuid4)),
                ('appt_date', models.DateField()),
                ('appt_time', models.TimeField()),
                ('time_slot_span', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.FloatField()),
                ('is_booked', models.BooleanField()),
                ('booked_appt_id', models.CharField()),
            ],
        ),
    ]
