# Generated by Django 6.0.7 on 2026-08-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_timeslot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_visit', models.CharField(max_length=200)),
                ('symptoms', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('timeslot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_form', to='appointment.timeslot')),
            ],
        ),
    ]
