# Generated by Django 6.0.6 on 2026-08-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_intakeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='booked_appt_id',
            field=models.CharField(max_length=255),
        ),
    ]
