# Generated by Django 6.0.6 on 2026-08-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointment', '0005_alter_timeslot_booked_appt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='booked_appt_id',
            field=models.ForeignKey(blank=True, db_column='booked_appt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to='accounts.patient'),
        ),
    ]
