# Generated by Django 6.0.6 on 2026-08-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_timeslot_booked_appt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='booked_appt_id',
            field=models.CharField(default=None),
        ),
    ]
