# Generated by Django 6.0.6 on 2026-08-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointment', '0008_alter_timeslot_booked_appt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='fk_patient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_forms', to='accounts.patient'),
        ),
    ]
